test:
  script:
  - apt-get update -qy
  - apt-get install -y python-dev python-pip
  - apt-get install python-numpy python-scipy python-matplotlib ipython ipython-notebook python-pandas python-sympy python-nose
  - pip install scikit-learn
  - pip install sklearn
  - pip install -r requirements.txt
  - apt-get install libjpeg libjpeg-dev libfreetype6 libfreetype6-dev zlib1g-dev
  - pip install PIL
  - pip install pytest
  - pip install pytest-cov
  - python -m pytest --cov=improc
